/*
  SQL Server DDL đồng bộ toàn bộ bảng cho dự án Quản lý Trung tâm Thương mại.
  Bản này đã cập nhật lại thiết kế báo cáo tài chính và báo cáo bảo trì mới.

  Cách dùng:
  - Chạy trên SSMS/Azure Data Studio bằng tài khoản có quyền tạo database.
  - Script sẽ DROP DATABASE QLTTTM nếu đã tồn tại.
*/

USE master;
GO

IF DB_ID('QLTTTM') IS NOT NULL
BEGIN
    ALTER DATABASE QLTTTM SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE QLTTTM;
END;
GO

CREATE DATABASE QLTTTM COLLATE Vietnamese_CI_AS;
GO

USE QLTTTM;
GO

IF NOT EXISTS (SELECT 1 FROM sys.server_principals WHERE name = 'backend_user')
BEGIN
    CREATE LOGIN backend_user WITH PASSWORD = 'Mk123!';
END;
GO

CREATE USER backend_user FOR LOGIN backend_user;
GO
ALTER ROLE db_owner ADD MEMBER backend_user;
GO

SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

BEGIN TRANSACTION;
GO

/* =========================================================
   1. RBAC VÀ HỒ SƠ NGƯỜI DÙNG
   ========================================================= */

CREATE TABLE dbo.VAITRO (
    MAVAITRO varchar(20) NOT NULL,
    TENVAITRO nvarchar(100) NOT NULL,
    MOTA nvarchar(255) NULL,
    TRANGTHAI nvarchar(30) NOT NULL,
    CONSTRAINT PK_VAITRO PRIMARY KEY (MAVAITRO),
    CONSTRAINT UQ_VAITRO_TENVAITRO UNIQUE (TENVAITRO),
    CONSTRAINT CK_VAITRO_TRANGTHAI CHECK (TRANGTHAI IN (N'Đang dùng', N'Ngừng dùng'))
);
GO

CREATE TABLE dbo.QUYEN (
    MAQUYEN varchar(20) NOT NULL,
    TENQUYEN nvarchar(100) NOT NULL,
    MODULE varchar(50) NOT NULL,
    HANHDONG varchar(50) NOT NULL,
    MOTA nvarchar(255) NULL,
    CONSTRAINT PK_QUYEN PRIMARY KEY (MAQUYEN),
    CONSTRAINT CK_QUYEN_HANHDONG CHECK (HANHDONG IN ('Xem', 'Tạo', 'Sửa', 'Xóa', 'Duyệt', 'Thanh toán', 'Import'))
);
GO

CREATE TABLE dbo.NHANVIEN (
    MANV varchar(20) NOT NULL,
    HOTEN nvarchar(100) NOT NULL,
    PHONGBAN nvarchar(50) NOT NULL,
    CHUCVU nvarchar(50) NOT NULL,
    SDT varchar(15) NULL,
    EMAIL varchar(100) NULL,
    TRANGTHAI nvarchar(30) NOT NULL CONSTRAINT DF_NHANVIEN_TRANGTHAI DEFAULT N'Đang làm',
    NGAYTAO datetime2 NOT NULL CONSTRAINT DF_NHANVIEN_NGAYTAO DEFAULT GETDATE(),
    CONSTRAINT PK_NHANVIEN PRIMARY KEY (MANV),
    CONSTRAINT CK_NHANVIEN_PHONGBAN CHECK (PHONGBAN IN (N'Quản trị hệ thống', N'Ban Quản Lý', N'Kinh doanh - Tài chính', N'Vận hành - Bảo trì')),
    CONSTRAINT CK_NHANVIEN_CHUCVU CHECK (CHUCVU IN (N'Quản trị viên', N'Ban Quản Lý', N'Trưởng phòng', N'Nhân viên')),
    CONSTRAINT CK_NHANVIEN_TRANGTHAI CHECK (TRANGTHAI IN (N'Đang làm', N'Nghỉ', N'Tạm khóa'))
);
GO

CREATE TABLE dbo.KHACHTHUE (
    MAKH varchar(20) NOT NULL,
    TENKHACH nvarchar(150) NOT NULL,
    CCCD_MST varchar(30) NOT NULL,
    SDT varchar(15) NULL,
    EMAIL varchar(100) NULL,
    DIACHI nvarchar(255) NULL,
    TRANGTHAI nvarchar(30) NOT NULL CONSTRAINT DF_KHACHTHUE_TRANGTHAI DEFAULT N'Đang thuê',
    NGAYTAO datetime2 NOT NULL CONSTRAINT DF_KHACHTHUE_NGAYTAO DEFAULT GETDATE(),
    CONSTRAINT PK_KHACHTHUE PRIMARY KEY (MAKH),
    CONSTRAINT UQ_KHACHTHUE_CCCD_MST UNIQUE (CCCD_MST),
    CONSTRAINT CK_KHACHTHUE_TRANGTHAI CHECK (TRANGTHAI IN (N'Đang thuê', N'Ngừng thuê'))
);
GO

CREATE TABLE dbo.MATBANG (
    MAMB varchar(20) NOT NULL,
    VITRI nvarchar(100) NOT NULL,
    TANG int NOT NULL,
    DIENTICH decimal(10,2) NOT NULL,
    LOAIMB nvarchar(50) NOT NULL,
    TRANGTHAI nvarchar(30) NOT NULL,
    GHICHU nvarchar(255) NULL,
    CONSTRAINT PK_MATBANG PRIMARY KEY (MAMB),
    CONSTRAINT CK_MATBANG_DIENTICH CHECK (DIENTICH > 0),
    CONSTRAINT CK_MATBANG_TRANGTHAI CHECK (TRANGTHAI IN (N'Còn trống', N'Đang thuê', N'Đang bảo trì'))
);
GO

CREATE TABLE dbo.TAIKHOAN (
    MATK varchar(20) NOT NULL,
    TENDANGNHAP varchar(50) NOT NULL,
    MATKHAU varchar(255) NOT NULL,
    TRANGTHAI nvarchar(20) NOT NULL CONSTRAINT DF_TAIKHOAN_TRANGTHAI DEFAULT N'Hoạt động',
    BATBUOC_DOIMK bit NOT NULL CONSTRAINT DF_TAIKHOAN_BATBUOC_DOIMK DEFAULT 1,
    SOLAN_DANGNHAPSAI int NOT NULL CONSTRAINT DF_TAIKHOAN_SOLAN_DANGNHAPSAI DEFAULT 0,
    KHOA_DEN datetime2 NULL,
    MANV varchar(20) NULL,
    MAKH varchar(20) NULL,
    MAVAITRO varchar(20) NOT NULL,
    NGAYTAO datetime2 NOT NULL CONSTRAINT DF_TAIKHOAN_NGAYTAO DEFAULT GETDATE(),
    CONSTRAINT PK_TAIKHOAN PRIMARY KEY (MATK),
    CONSTRAINT UQ_TAIKHOAN_TENDANGNHAP UNIQUE (TENDANGNHAP),
    CONSTRAINT FK_TAIKHOAN_NHANVIEN FOREIGN KEY (MANV) REFERENCES dbo.NHANVIEN(MANV),
    CONSTRAINT FK_TAIKHOAN_KHACHTHUE FOREIGN KEY (MAKH) REFERENCES dbo.KHACHTHUE(MAKH),
    CONSTRAINT FK_TAIKHOAN_VAITRO FOREIGN KEY (MAVAITRO) REFERENCES dbo.VAITRO(MAVAITRO),
    CONSTRAINT CK_TAIKHOAN_TRANGTHAI CHECK (TRANGTHAI IN (N'Hoạt động', N'Vô hiệu')),
    CONSTRAINT CK_TAIKHOAN_SOLAN_DANGNHAPSAI CHECK (SOLAN_DANGNHAPSAI >= 0),
    CONSTRAINT CK_TAIKHOAN_CHU_THE CHECK ((MANV IS NOT NULL AND MAKH IS NULL) OR (MANV IS NULL AND MAKH IS NOT NULL))
);
GO

CREATE TABLE dbo.VAITRO_QUYEN (
    MAVAITRO varchar(20) NOT NULL,
    MAQUYEN varchar(20) NOT NULL,
    CONSTRAINT PK_VAITRO_QUYEN PRIMARY KEY (MAVAITRO, MAQUYEN),
    CONSTRAINT FK_VAITRO_QUYEN_VAITRO FOREIGN KEY (MAVAITRO) REFERENCES dbo.VAITRO(MAVAITRO),
    CONSTRAINT FK_VAITRO_QUYEN_QUYEN FOREIGN KEY (MAQUYEN) REFERENCES dbo.QUYEN(MAQUYEN)
);
GO

/* =========================================================
   2. HỢP ĐỒNG VÀ YÊU CẦU THUÊ THÊM
   ========================================================= */

CREATE TABLE dbo.YC_THUETHEM (
    MAYC varchar(20) NOT NULL,
    MAKH varchar(20) NOT NULL,
    MAMB varchar(20) NOT NULL,
    MANV_DUYET varchar(20) NULL,
    NGAYGUI datetime2 NOT NULL CONSTRAINT DF_YC_THUETHEM_NGAYGUI DEFAULT GETDATE(),
    LYDO nvarchar(max) NOT NULL,
    TRANGTHAI nvarchar(30) NOT NULL CONSTRAINT DF_YC_THUETHEM_TRANGTHAI DEFAULT N'Chờ duyệt',
    NGAYDUYET datetime2 NULL,
    LYDO_TUCHOI nvarchar(max) NULL,
    GHICHU nvarchar(255) NULL,
    CONSTRAINT PK_YC_THUETHEM PRIMARY KEY (MAYC),
    CONSTRAINT FK_YC_THUETHEM_KHACHTHUE FOREIGN KEY (MAKH) REFERENCES dbo.KHACHTHUE(MAKH),
    CONSTRAINT FK_YC_THUETHEM_MATBANG FOREIGN KEY (MAMB) REFERENCES dbo.MATBANG(MAMB),
    CONSTRAINT FK_YC_THUETHEM_NHANVIEN_DUYET FOREIGN KEY (MANV_DUYET) REFERENCES dbo.NHANVIEN(MANV),
    CONSTRAINT CK_YC_THUETHEM_TRANGTHAI CHECK (TRANGTHAI IN (N'Chờ duyệt', N'Đã duyệt - Chờ số hóa hợp đồng', N'Từ chối', N'Đã tạo hợp đồng')),
    CONSTRAINT CK_YC_THUETHEM_TUCHOI_CO_LYDO CHECK (TRANGTHAI <> N'Từ chối' OR LYDO_TUCHOI IS NOT NULL)
);
GO

CREATE TABLE dbo.HOPDONG (
    MAHD varchar(20) NOT NULL,
    MAKH varchar(20) NOT NULL,
    MAMB varchar(20) NOT NULL,
    MANV_SOHOA varchar(20) NOT NULL,
    MAYC varchar(20) NULL,
    NGAYBATDAU date NOT NULL,
    NGAYKETTHUC date NOT NULL,
    GIATHUETHANG decimal(18,2) NOT NULL,
    TRANGTHAI nvarchar(30) NOT NULL,
    NGAYSOHOA datetime2 NOT NULL CONSTRAINT DF_HOPDONG_NGAYSOHOA DEFAULT GETDATE(),
    CONSTRAINT PK_HOPDONG PRIMARY KEY (MAHD),
    CONSTRAINT FK_HOPDONG_KHACHTHUE FOREIGN KEY (MAKH) REFERENCES dbo.KHACHTHUE(MAKH),
    CONSTRAINT FK_HOPDONG_MATBANG FOREIGN KEY (MAMB) REFERENCES dbo.MATBANG(MAMB),
    CONSTRAINT FK_HOPDONG_NHANVIEN_SOHOA FOREIGN KEY (MANV_SOHOA) REFERENCES dbo.NHANVIEN(MANV),
    CONSTRAINT FK_HOPDONG_YC_THUETHEM FOREIGN KEY (MAYC) REFERENCES dbo.YC_THUETHEM(MAYC),
    CONSTRAINT CK_HOPDONG_NGAY CHECK (NGAYKETTHUC > NGAYBATDAU),
    CONSTRAINT CK_HOPDONG_GIATHUETHANG CHECK (GIATHUETHANG > 0),
    CONSTRAINT CK_HOPDONG_TRANGTHAI CHECK (TRANGTHAI IN (N'Đang hiệu lực', N'Hết hạn', N'Đã hủy'))
);
GO

/* =========================================================
   3. NHẬT KÝ, THÔNG BÁO
   ========================================================= */

CREATE TABLE dbo.NHATKY (
    MANHATKY varchar(20) NOT NULL,
    MATK varchar(20) NOT NULL,
    THOIGIAN datetime2 NOT NULL CONSTRAINT DF_NHATKY_THOIGIAN DEFAULT GETDATE(),
    HANHDONG nvarchar(50) NOT NULL,
    DOITUONG nvarchar(100) NOT NULL,
    MADOITUONG varchar(20) NULL,
    GIATRICU nvarchar(max) NULL,
    GIATRIMOI nvarchar(max) NULL,
    CHITIET nvarchar(max) NULL,
    IP_ADDRESS varchar(45) NULL,
    CONSTRAINT PK_NHATKY PRIMARY KEY (MANHATKY),
    CONSTRAINT FK_NHATKY_TAIKHOAN FOREIGN KEY (MATK) REFERENCES dbo.TAIKHOAN(MATK),
    CONSTRAINT CK_NHATKY_HANHDONG CHECK (HANHDONG IN (N'Đăng nhập', N'Đăng xuất', N'Tạo mới', N'Cập nhật', N'Xóa', N'Duyệt', N'Vượt quyền'))
);
GO

CREATE TABLE dbo.THONGBAO (
    MATB varchar(20) NOT NULL,
    MANV_BANHANH varchar(20) NOT NULL,
    TIEUDE nvarchar(255) NOT NULL,
    NOIDUNG nvarchar(max) NOT NULL,
    LOAITHONGBAO nvarchar(50) NOT NULL,
    DOITUONGNHAN nvarchar(50) NOT NULL,
    NGAYBANHANH datetime2 NOT NULL CONSTRAINT DF_THONGBAO_NGAYBANHANH DEFAULT GETDATE(),
    TRANGTHAI nvarchar(30) NOT NULL CONSTRAINT DF_THONGBAO_TRANGTHAI DEFAULT N'Đã ban hành',
    CONSTRAINT PK_THONGBAO PRIMARY KEY (MATB),
    CONSTRAINT FK_THONGBAO_NHANVIEN_BANHANH FOREIGN KEY (MANV_BANHANH) REFERENCES dbo.NHANVIEN(MANV),
    CONSTRAINT CK_THONGBAO_LOAI CHECK (LOAITHONGBAO IN (N'Thông báo', N'Kế hoạch', N'Quy định')),
    CONSTRAINT CK_THONGBAO_DOITUONGNHAN CHECK (DOITUONGNHAN IN (N'Toàn hệ thống', N'Nội bộ', N'Khách thuê')),
    CONSTRAINT CK_THONGBAO_TRANGTHAI CHECK (TRANGTHAI IN (N'Đã ban hành', N'Đã thu hồi'))
);
GO

/* =========================================================
   4. TÀI CHÍNH, ĐIỆN NƯỚC, THANH TOÁN
   ========================================================= */

CREATE TABLE dbo.CHISODIENNUOC (
    MACSDN varchar(20) NOT NULL,
    MAMB varchar(20) NOT NULL,
    MANV_NHAP varchar(20) NOT NULL,
    THANG int NOT NULL,
    NAM int NOT NULL,
    CHISODIENDAU decimal(18,2) NOT NULL,
    CHISODIENCUOI decimal(18,2) NOT NULL,
    CHISONUOCDAU decimal(18,2) NOT NULL,
    CHISONUOCCUOI decimal(18,2) NOT NULL,
    NGAYNHAP datetime2 NOT NULL CONSTRAINT DF_CHISODIENNUOC_NGAYNHAP DEFAULT GETDATE(),
    CONSTRAINT PK_CHISODIENNUOC PRIMARY KEY (MACSDN),
    CONSTRAINT FK_CHISODIENNUOC_MATBANG FOREIGN KEY (MAMB) REFERENCES dbo.MATBANG(MAMB),
    CONSTRAINT FK_CHISODIENNUOC_NHANVIEN_NHAP FOREIGN KEY (MANV_NHAP) REFERENCES dbo.NHANVIEN(MANV),
    CONSTRAINT UQ_CHISODIENNUOC_MAMB_THANG_NAM UNIQUE (MAMB, THANG, NAM),
    CONSTRAINT CK_CHISODIENNUOC_THANG CHECK (THANG BETWEEN 1 AND 12),
    CONSTRAINT CK_CHISODIENNUOC_CHISODIENDAU CHECK (CHISODIENDAU >= 0),
    CONSTRAINT CK_CHISODIENNUOC_CHISODIENCUOI CHECK (CHISODIENCUOI >= CHISODIENDAU),
    CONSTRAINT CK_CHISODIENNUOC_CHISONUOCDAU CHECK (CHISONUOCDAU >= 0),
    CONSTRAINT CK_CHISODIENNUOC_CHISONUOCCUOI CHECK (CHISONUOCCUOI >= CHISONUOCDAU)
);
GO

CREATE TABLE dbo.DULIEU_IMPORT_TAICHINH (
    MAIMPORT varchar(20) NOT NULL,
    MAHD varchar(20) NOT NULL,
    THANG int NOT NULL,
    NAM int NOT NULL,
    LOAIKHOAN nvarchar(50) NOT NULL,
    SOTIEN decimal(18,2) NOT NULL,
    GHICHU nvarchar(255) NULL,
    MANV_IMPORT varchar(20) NOT NULL,
    THOIGIAN_IMPORT datetime2 NOT NULL CONSTRAINT DF_DULIEU_IMPORT_TAICHINH_THOIGIAN DEFAULT GETDATE(),
    TENFILE nvarchar(255) NULL,
    DONG_EXCEL int NULL,
    TRANGTHAI nvarchar(30) NOT NULL,
    LOI_CHITIET nvarchar(255) NULL,
    CONSTRAINT PK_DULIEU_IMPORT_TAICHINH PRIMARY KEY (MAIMPORT),
    CONSTRAINT FK_DULIEU_IMPORT_TAICHINH_HOPDONG FOREIGN KEY (MAHD) REFERENCES dbo.HOPDONG(MAHD),
    CONSTRAINT FK_DULIEU_IMPORT_TAICHINH_NHANVIEN_IMPORT FOREIGN KEY (MANV_IMPORT) REFERENCES dbo.NHANVIEN(MANV),
    CONSTRAINT CK_DULIEU_IMPORT_TAICHINH_THANG CHECK (THANG BETWEEN 1 AND 12),
    CONSTRAINT CK_DULIEU_IMPORT_TAICHINH_LOAIKHOAN CHECK (LOAIKHOAN IN (N'Tiền thuê', N'Tiền điện', N'Tiền nước', N'Phí bảo trì', N'Hoàn trả')),
    CONSTRAINT CK_DULIEU_IMPORT_TAICHINH_SOTIEN CHECK (SOTIEN > 0),
    CONSTRAINT CK_DULIEU_IMPORT_TAICHINH_DONG_EXCEL CHECK (DONG_EXCEL IS NULL OR DONG_EXCEL > 0),
    CONSTRAINT CK_DULIEU_IMPORT_TAICHINH_TRANGTHAI CHECK (TRANGTHAI IN (N'Hợp lệ', N'Lỗi', N'Đã dùng tính công nợ'))
);
GO

CREATE TABLE dbo.CONGNO (
    MACN varchar(20) NOT NULL,
    MAHD varchar(20) NOT NULL,
    THANG int NOT NULL,
    NAM int NOT NULL,
    TIENTHUE decimal(18,2) NOT NULL,
    TIENDIEN decimal(18,2) NOT NULL,
    TIENNUOC decimal(18,2) NOT NULL,
    PHIBAOTRI decimal(18,2) NOT NULL CONSTRAINT DF_CONGNO_PHIBAOTRI DEFAULT 0,
    TIENHOAN decimal(18,2) NOT NULL CONSTRAINT DF_CONGNO_TIENHOAN DEFAULT 0,
    TONGTIEN decimal(18,2) NOT NULL,
    HAN_THANHTOAN date NULL,
    TRANGTHAI nvarchar(30) NOT NULL CONSTRAINT DF_CONGNO_TRANGTHAI DEFAULT N'Chưa thanh toán',
    NGAYLAP datetime2 NOT NULL CONSTRAINT DF_CONGNO_NGAYLAP DEFAULT GETDATE(),
    CONSTRAINT PK_CONGNO PRIMARY KEY (MACN),
    CONSTRAINT FK_CONGNO_HOPDONG FOREIGN KEY (MAHD) REFERENCES dbo.HOPDONG(MAHD),
    CONSTRAINT UQ_CONGNO_MAHD_THANG_NAM UNIQUE (MAHD, THANG, NAM),
    CONSTRAINT CK_CONGNO_THANG CHECK (THANG BETWEEN 1 AND 12),
    CONSTRAINT CK_CONGNO_TIENTHUE CHECK (TIENTHUE >= 0),
    CONSTRAINT CK_CONGNO_TIENDIEN CHECK (TIENDIEN >= 0),
    CONSTRAINT CK_CONGNO_TIENNUOC CHECK (TIENNUOC >= 0),
    CONSTRAINT CK_CONGNO_PHIBAOTRI CHECK (PHIBAOTRI >= 0),
    CONSTRAINT CK_CONGNO_TIENHOAN CHECK (TIENHOAN >= 0),
    CONSTRAINT CK_CONGNO_TONGTIEN_KHONGAM CHECK (TONGTIEN >= 0),
    CONSTRAINT CK_CONGNO_TONGTIEN_CONGTHUC CHECK (TONGTIEN = TIENTHUE + TIENDIEN + TIENNUOC + PHIBAOTRI - TIENHOAN),
    CONSTRAINT CK_CONGNO_TRANGTHAI CHECK (TRANGTHAI IN (N'Chưa thanh toán', N'Đã thanh toán', N'Quá hạn'))
);
GO

CREATE TABLE dbo.HOADON (
    MAHOADON varchar(20) NOT NULL,
    MACN varchar(20) NOT NULL,
    MAKH varchar(20) NOT NULL,
    TIENTHUE decimal(18,2) NOT NULL,
    TIENDIEN decimal(18,2) NOT NULL,
    TIENNUOC decimal(18,2) NOT NULL,
    PHIBAOTRI decimal(18,2) NOT NULL CONSTRAINT DF_HOADON_PHIBAOTRI DEFAULT 0,
    TIENHOAN decimal(18,2) NOT NULL CONSTRAINT DF_HOADON_TIENHOAN DEFAULT 0,
    TONGTIEN decimal(18,2) NOT NULL,
    SOTIEN decimal(18,2) NOT NULL,
    PHUONGTHUC nvarchar(50) NOT NULL,
    MAGIAODICHCONG varchar(100) NULL,
    THOIGIANGD datetime2 NOT NULL CONSTRAINT DF_HOADON_THOIGIANGD DEFAULT GETDATE(),
    TRANGTHAI nvarchar(30) NOT NULL CONSTRAINT DF_HOADON_TRANGTHAI DEFAULT N'Đang xử lý',
    NOIDUNG nvarchar(255) NULL,
    GHICHU nvarchar(255) NULL,
    CONSTRAINT PK_HOADON PRIMARY KEY (MAHOADON),
    CONSTRAINT FK_HOADON_CONGNO FOREIGN KEY (MACN) REFERENCES dbo.CONGNO(MACN),
    CONSTRAINT FK_HOADON_KHACHTHUE FOREIGN KEY (MAKH) REFERENCES dbo.KHACHTHUE(MAKH),
    CONSTRAINT CK_HOADON_TIENTHUE CHECK (TIENTHUE >= 0),
    CONSTRAINT CK_HOADON_TIENDIEN CHECK (TIENDIEN >= 0),
    CONSTRAINT CK_HOADON_TIENNUOC CHECK (TIENNUOC >= 0),
    CONSTRAINT CK_HOADON_PHIBAOTRI CHECK (PHIBAOTRI >= 0),
    CONSTRAINT CK_HOADON_TIENHOAN CHECK (TIENHOAN >= 0),
    CONSTRAINT CK_HOADON_TONGTIEN_KHONGAM CHECK (TONGTIEN >= 0),
    CONSTRAINT CK_HOADON_TONGTIEN_CONGTHUC CHECK (TONGTIEN = TIENTHUE + TIENDIEN + TIENNUOC + PHIBAOTRI - TIENHOAN),
    CONSTRAINT CK_HOADON_SOTIEN_DUONG CHECK (SOTIEN > 0),
    CONSTRAINT CK_HOADON_SOTIEN_TONGTIEN CHECK (SOTIEN = TONGTIEN),
    CONSTRAINT CK_HOADON_PHUONGTHUC CHECK (PHUONGTHUC IN (N'VNPay', N'MoMo', N'ZaloPay')),
    CONSTRAINT CK_HOADON_TRANGTHAI CHECK (TRANGTHAI IN (N'Đang xử lý', N'Thành công', N'Thất bại'))
);
GO

CREATE TABLE dbo.BAOCAOTAICHINH (
    MABC varchar(20) NOT NULL,
    MANV varchar(20) NOT NULL,
    THANG int NOT NULL,
    NAM int NOT NULL,
    KYCHOT varchar(7) NOT NULL,
    NGAYLAP datetime2 NOT NULL CONSTRAINT DF_BAOCAOTAICHINH_NGAYLAP DEFAULT GETDATE(),
    CONSTRAINT PK_BAOCAOTAICHINH PRIMARY KEY (MABC),
    CONSTRAINT FK_BAOCAOTAICHINH_NHANVIEN FOREIGN KEY (MANV) REFERENCES dbo.NHANVIEN(MANV),
    CONSTRAINT UQ_BAOCAOTAICHINH_THANG_NAM UNIQUE (THANG, NAM),
    CONSTRAINT CK_BAOCAOTAICHINH_THANG CHECK (THANG BETWEEN 1 AND 12),
    CONSTRAINT CK_BAOCAOTAICHINH_NAM CHECK (NAM BETWEEN 2000 AND 2100)
);
GO

CREATE TABLE dbo.BAOCAOTAICHINH_CHITIET (
    MABC varchar(20) NOT NULL,
    STT int NOT NULL,
    MAHD varchar(20) NOT NULL,
    MAKH varchar(20) NOT NULL,
    MAMB varchar(20) NOT NULL,
    KY varchar(7) NOT NULL,
    TIENTHUE decimal(18,2) NOT NULL,
    TIENDIEN decimal(18,2) NOT NULL,
    TIENNUOC decimal(18,2) NOT NULL,
    TIENHOANTRA decimal(18,2) NOT NULL,
    CHIPHI_BAOTRI decimal(18,2) NOT NULL,
    TONGTIEN decimal(18,2) NOT NULL,
    DA_THANH_TOAN decimal(18,2) NOT NULL,
    NO decimal(18,2) NOT NULL,
    CONSTRAINT PK_BAOCAOTAICHINH_CHITIET PRIMARY KEY (MABC, STT),
    CONSTRAINT FK_BCTC_CT_BAOCAOTAICHINH FOREIGN KEY (MABC) REFERENCES dbo.BAOCAOTAICHINH(MABC) ON DELETE CASCADE,
    CONSTRAINT FK_BCTC_CT_HOPDONG FOREIGN KEY (MAHD) REFERENCES dbo.HOPDONG(MAHD),
    CONSTRAINT CK_BCTC_CT_STT CHECK (STT > 0),
    CONSTRAINT CK_BCTC_CT_TIENTHUE CHECK (TIENTHUE >= 0),
    CONSTRAINT CK_BCTC_CT_TIENDIEN CHECK (TIENDIEN >= 0),
    CONSTRAINT CK_BCTC_CT_TIENNUOC CHECK (TIENNUOC >= 0),
    CONSTRAINT CK_BCTC_CT_TIENHOANTRA CHECK (TIENHOANTRA >= 0),
    CONSTRAINT CK_BCTC_CT_CHIPHI_BAOTRI CHECK (CHIPHI_BAOTRI >= 0),
    CONSTRAINT CK_BCTC_CT_TONGTIEN CHECK (TONGTIEN >= 0),
    CONSTRAINT CK_BCTC_CT_DA_THANH_TOAN CHECK (DA_THANH_TOAN >= 0),
    CONSTRAINT CK_BCTC_CT_NO CHECK (NO >= 0)
);
GO

/* =========================================================
   5. SỰ CỐ VÀ BÁO CÁO BẢO TRÌ
   ========================================================= */

CREATE TABLE dbo.SK_BAOTRI (
    MASUCO varchar(20) NOT NULL,
    MAMB varchar(20) NOT NULL,
    MAKH varchar(20) NOT NULL,
    MANV_DUYET varchar(20) NULL,
    MANV_PHANCONG varchar(20) NULL,
    MANV_XULY varchar(20) NULL,
    NGAYGUI datetime2 NOT NULL CONSTRAINT DF_SK_BAOTRI_NGAYGUI DEFAULT GETDATE(),
    MOTA nvarchar(max) NOT NULL,
    TRANGTHAI nvarchar(30) NOT NULL CONSTRAINT DF_SK_BAOTRI_TRANGTHAI DEFAULT N'Chờ duyệt',
    LYDO_TUCHOI nvarchar(max) NULL,
    NGAYDUYET datetime2 NULL,
    NGAYPHANCONG datetime2 NULL,
    NGAYHOANTHANH datetime2 NULL,
    KETQUA nvarchar(max) NULL,
    CHIPHI decimal(18,2) NULL,
    CONSTRAINT PK_SK_BAOTRI PRIMARY KEY (MASUCO),
    CONSTRAINT FK_SK_BAOTRI_MATBANG FOREIGN KEY (MAMB) REFERENCES dbo.MATBANG(MAMB),
    CONSTRAINT FK_SK_BAOTRI_KHACHTHUE FOREIGN KEY (MAKH) REFERENCES dbo.KHACHTHUE(MAKH),
    CONSTRAINT FK_SK_BAOTRI_NHANVIEN_DUYET FOREIGN KEY (MANV_DUYET) REFERENCES dbo.NHANVIEN(MANV),
    CONSTRAINT FK_SK_BAOTRI_NHANVIEN_PHANCONG FOREIGN KEY (MANV_PHANCONG) REFERENCES dbo.NHANVIEN(MANV),
    CONSTRAINT FK_SK_BAOTRI_NHANVIEN_XULY FOREIGN KEY (MANV_XULY) REFERENCES dbo.NHANVIEN(MANV),
    CONSTRAINT CK_SK_BAOTRI_TRANGTHAI CHECK (TRANGTHAI IN (N'Chờ duyệt', N'Đã duyệt', N'Từ chối', N'Đang xử lý', N'Hoàn thành')),
    CONSTRAINT CK_SK_BAOTRI_CHIPHI CHECK (CHIPHI IS NULL OR CHIPHI >= 0),
    CONSTRAINT CK_SK_BAOTRI_TUCHOI_CO_LYDO CHECK (TRANGTHAI <> N'Từ chối' OR LYDO_TUCHOI IS NOT NULL)
);
GO

CREATE TABLE dbo.BAOCAOBAOTRI (
    MABC varchar(20) NOT NULL,
    MANV varchar(20) NOT NULL,
    THANG int NOT NULL,
    NAM int NOT NULL,
    KYCHOT varchar(7) NOT NULL,
    NGAYLAP datetime2 NOT NULL CONSTRAINT DF_BAOCAOBAOTRI_NGAYLAP DEFAULT GETDATE(),
    CONSTRAINT PK_BAOCAOBAOTRI PRIMARY KEY (MABC),
    CONSTRAINT FK_BAOCAOBAOTRI_NHANVIEN FOREIGN KEY (MANV) REFERENCES dbo.NHANVIEN(MANV),
    CONSTRAINT UQ_BAOCAOBAOTRI_THANG_NAM UNIQUE (THANG, NAM),
    CONSTRAINT CK_BAOCAOBAOTRI_THANG CHECK (THANG BETWEEN 1 AND 12),
    CONSTRAINT CK_BAOCAOBAOTRI_NAM CHECK (NAM BETWEEN 2000 AND 2100)
);
GO

CREATE TABLE dbo.BAOCAOBAOTRI_CHITIET (
    MABC varchar(20) NOT NULL,
    STT int NOT NULL,
    MAYC varchar(20) NOT NULL,
    MAMB varchar(20) NOT NULL,
    NGAYYC datetime2 NOT NULL,
    MOTA nvarchar(max) NOT NULL,
    TRANGTHAI nvarchar(30) NOT NULL,
    NGAYGIAIQUYET datetime2 NULL,
    KETQUA nvarchar(max) NULL,
    CONSTRAINT PK_BAOCAOBAOTRI_CHITIET PRIMARY KEY (MABC, STT),
    CONSTRAINT FK_BCBT_CT_BAOCAOBAOTRI FOREIGN KEY (MABC) REFERENCES dbo.BAOCAOBAOTRI(MABC) ON DELETE CASCADE,
    CONSTRAINT FK_BCBT_CT_SK_BAOTRI FOREIGN KEY (MAYC) REFERENCES dbo.SK_BAOTRI(MASUCO),
    CONSTRAINT FK_BCBT_CT_MATBANG FOREIGN KEY (MAMB) REFERENCES dbo.MATBANG(MAMB),
    CONSTRAINT CK_BCBT_CT_STT CHECK (STT > 0),
    CONSTRAINT CK_BCBT_CT_TRANGTHAI CHECK (TRANGTHAI IN (N'Chờ duyệt', N'Đã duyệt', N'Từ chối', N'Đang xử lý', N'Hoàn thành'))
);
GO

/* =========================================================
   6. FILTERED UNIQUE INDEX
   ========================================================= */

CREATE UNIQUE INDEX UX_NHANVIEN_EMAIL_NOTNULL ON dbo.NHANVIEN(EMAIL) WHERE EMAIL IS NOT NULL;
GO
CREATE UNIQUE INDEX UX_TAIKHOAN_MANV_NOTNULL ON dbo.TAIKHOAN(MANV) WHERE MANV IS NOT NULL;
GO
CREATE UNIQUE INDEX UX_TAIKHOAN_MAKH_NOTNULL ON dbo.TAIKHOAN(MAKH) WHERE MAKH IS NOT NULL;
GO
CREATE UNIQUE INDEX UX_HOPDONG_MAYC_NOTNULL ON dbo.HOPDONG(MAYC) WHERE MAYC IS NOT NULL;
GO
CREATE UNIQUE INDEX UX_HOPDONG_MAMB_DANGHIEULUC ON dbo.HOPDONG(MAMB) WHERE TRANGTHAI = N'Đang hiệu lực';
GO
CREATE UNIQUE INDEX UX_YC_THUETHEM_PENDING_MAKH_MAMB ON dbo.YC_THUETHEM(MAKH, MAMB) WHERE TRANGTHAI = N'Chờ duyệt';
GO
CREATE UNIQUE INDEX UX_HOADON_MACN_THANHCONG ON dbo.HOADON(MACN) WHERE TRANGTHAI = N'Thành công';
GO

/* =========================================================
   7. INDEX TRA CỨU
   ========================================================= */

CREATE INDEX IX_TAIKHOAN_MAVAITRO_TRANGTHAI ON dbo.TAIKHOAN(MAVAITRO, TRANGTHAI);
GO
CREATE INDEX IX_TAIKHOAN_MANV_MAKH ON dbo.TAIKHOAN(MANV, MAKH);
GO
CREATE INDEX IX_NHANVIEN_PHONGBAN_CHUCVU ON dbo.NHANVIEN(PHONGBAN, CHUCVU);
GO
CREATE INDEX IX_KHACHTHUE_SDT_EMAIL ON dbo.KHACHTHUE(SDT, EMAIL);
GO
CREATE INDEX IX_KHACHTHUE_TRANGTHAI ON dbo.KHACHTHUE(TRANGTHAI);
GO
CREATE INDEX IX_MATBANG_TRANGTHAI_TANG_LOAIMB ON dbo.MATBANG(TRANGTHAI, TANG, LOAIMB);
GO
CREATE INDEX IX_MATBANG_DIENTICH ON dbo.MATBANG(DIENTICH);
GO
CREATE INDEX IX_HOPDONG_MAKH_TRANGTHAI ON dbo.HOPDONG(MAKH, TRANGTHAI);
GO
CREATE INDEX IX_HOPDONG_MAMB_TRANGTHAI ON dbo.HOPDONG(MAMB, TRANGTHAI);
GO
CREATE INDEX IX_HOPDONG_NGAYBATDAU_NGAYKETTHUC ON dbo.HOPDONG(NGAYBATDAU, NGAYKETTHUC);
GO
CREATE INDEX IX_NHATKY_MATK_THOIGIAN ON dbo.NHATKY(MATK, THOIGIAN);
GO
CREATE INDEX IX_NHATKY_HANHDONG_DOITUONG ON dbo.NHATKY(HANHDONG, DOITUONG);
GO
CREATE INDEX IX_CHISODIENNUOC_MANV_NGAY ON dbo.CHISODIENNUOC(MANV_NHAP, NGAYNHAP);
GO
CREATE INDEX IX_DULIEU_IMPORT_TAICHINH_MAHD_THANG_NAM ON dbo.DULIEU_IMPORT_TAICHINH(MAHD, THANG, NAM);
GO
CREATE INDEX IX_DULIEU_IMPORT_TAICHINH_MANV_THOIGIAN ON dbo.DULIEU_IMPORT_TAICHINH(MANV_IMPORT, THOIGIAN_IMPORT);
GO
CREATE INDEX IX_DULIEU_IMPORT_TAICHINH_TRANGTHAI ON dbo.DULIEU_IMPORT_TAICHINH(TRANGTHAI);
GO
CREATE INDEX IX_CONGNO_TRANGTHAI_HAN_THANHTOAN ON dbo.CONGNO(TRANGTHAI, HAN_THANHTOAN);
GO
CREATE INDEX IX_CONGNO_THANG_NAM_TRANGTHAI ON dbo.CONGNO(THANG, NAM, TRANGTHAI);
GO
CREATE INDEX IX_HOADON_MACN_TRANGTHAI ON dbo.HOADON(MACN, TRANGTHAI);
GO
CREATE INDEX IX_HOADON_MAKH_THOIGIANGD ON dbo.HOADON(MAKH, THOIGIANGD);
GO
CREATE INDEX IX_HOADON_MAGIAODICHCONG ON dbo.HOADON(MAGIAODICHCONG);
GO
CREATE INDEX IX_BAOCAOTAICHINH_THANG_NAM ON dbo.BAOCAOTAICHINH(THANG, NAM);
GO
CREATE INDEX IX_BAOCAOTAICHINH_MANV_NGAYLAP ON dbo.BAOCAOTAICHINH(MANV, NGAYLAP);
GO
CREATE INDEX IX_BCTC_CT_MAHD ON dbo.BAOCAOTAICHINH_CHITIET(MAHD);
GO
CREATE INDEX IX_BCTC_CT_MAKH_MAMB ON dbo.BAOCAOTAICHINH_CHITIET(MAKH, MAMB);
GO
CREATE INDEX IX_SK_BAOTRI_MAMB_TRANGTHAI ON dbo.SK_BAOTRI(MAMB, TRANGTHAI);
GO
CREATE INDEX IX_SK_BAOTRI_MAKH_NGAYGUI ON dbo.SK_BAOTRI(MAKH, NGAYGUI);
GO
CREATE INDEX IX_SK_BAOTRI_MANV_XULY_TRANGTHAI ON dbo.SK_BAOTRI(MANV_XULY, TRANGTHAI);
GO
CREATE INDEX IX_SK_BAOTRI_MANV_DUYET_PHANCONG ON dbo.SK_BAOTRI(MANV_DUYET, MANV_PHANCONG);
GO
CREATE INDEX IX_BAOCAOBAOTRI_THANG_NAM ON dbo.BAOCAOBAOTRI(THANG, NAM);
GO
CREATE INDEX IX_BAOCAOBAOTRI_MANV_NGAYLAP ON dbo.BAOCAOBAOTRI(MANV, NGAYLAP);
GO
CREATE INDEX IX_BCBT_CT_MAYC ON dbo.BAOCAOBAOTRI_CHITIET(MAYC);
GO
CREATE INDEX IX_BCBT_CT_MAMB_TRANGTHAI ON dbo.BAOCAOBAOTRI_CHITIET(MAMB, TRANGTHAI);
GO
CREATE INDEX IX_YC_THUETHEM_MAKH_MAMB_TRANGTHAI ON dbo.YC_THUETHEM(MAKH, MAMB, TRANGTHAI);
GO
CREATE INDEX IX_YC_THUETHEM_MAMB_TRANGTHAI ON dbo.YC_THUETHEM(MAMB, TRANGTHAI);
GO
CREATE INDEX IX_YC_THUETHEM_MANV_DUYET_NGAYDUYET ON dbo.YC_THUETHEM(MANV_DUYET, NGAYDUYET);
GO
CREATE INDEX IX_VAITRO_TRANGTHAI ON dbo.VAITRO(TRANGTHAI);
GO
CREATE INDEX IX_QUYEN_MODULE_HANHDONG ON dbo.QUYEN(MODULE, HANHDONG);
GO
CREATE INDEX IX_THONGBAO_DOITUONG_TRANGTHAI ON dbo.THONGBAO(DOITUONGNHAN, TRANGTHAI);
GO
CREATE INDEX IX_THONGBAO_LOAI_NGAY ON dbo.THONGBAO(LOAITHONGBAO, NGAYBANHANH);
GO

COMMIT TRANSACTION;
GO

SELECT 'INIT_ALL_TABLES_SYNC_DONE' AS RESULT;
GO
