import {
  AppstoreOutlined,
  AuditOutlined,
  ContainerOutlined,
  CreditCardOutlined,
  FileExcelOutlined,
  FileProtectOutlined,
  HomeOutlined,
  NotificationOutlined,
  PieChartOutlined,
  ProfileOutlined,
  SafetyCertificateOutlined,
  ShopOutlined,
  TeamOutlined,
  ToolOutlined,
  ThunderboltOutlined,
} from "@ant-design/icons";

import { ROLE } from "./roles";

export const ROUTES = {
  LOGIN: "/login",
  DASHBOARD: "/",
  ACCOUNTS: "/system/accounts",
  RBAC: "/system/rbac",
  AUDIT: "/system/audit",
  PREMISES: "/premises",
  CONTRACTS: "/contracts",
  MY_CONTRACTS: "/contracts/cua-toi",
  RENT_REQUESTS: "/yeu-cau-thue-them",
  DEBTS: "/finance/cong-no",
  MY_DEBTS: "/finance/cong-no-cua-toi",
  PAYMENT: "/finance/thanh-toan",
  FINANCIAL_IMPORT: "/finance/import",
  FINANCIAL_REPORTS: "/reports/financial",
  METER_READINGS: "/maintenance/chi-so-dien-nuoc",
  INCIDENTS: "/maintenance/su-co",
  MAINTENANCE_REPORTS: "/reports/maintenance",
  NOTIFICATIONS: "/notifications",
};

export const routePermissions = {
  [ROUTES.DASHBOARD]: [
    ROLE.QTV,
    ROLE.BQL,
    ROLE.TP_KDTC,
    ROLE.NV_KDTC,
    ROLE.TP_VHBT,
    ROLE.NV_VHBT,
    ROLE.KHACH_THUE,
  ],
  [ROUTES.ACCOUNTS]: [ROLE.QTV],
  [ROUTES.RBAC]: [ROLE.QTV],
  [ROUTES.AUDIT]: [ROLE.QTV, ROLE.BQL],
  [ROUTES.PREMISES]: [ROLE.BQL, ROLE.TP_VHBT, ROLE.NV_VHBT, ROLE.KHACH_THUE],
  [ROUTES.CONTRACTS]: [ROLE.BQL, ROLE.TP_KDTC, ROLE.NV_KDTC],
  [ROUTES.MY_CONTRACTS]: [ROLE.KHACH_THUE],
  [ROUTES.RENT_REQUESTS]: [ROLE.BQL, ROLE.KHACH_THUE],
  [ROUTES.DEBTS]: [ROLE.TP_KDTC, ROLE.NV_KDTC],
  [ROUTES.MY_DEBTS]: [ROLE.KHACH_THUE],
  [ROUTES.PAYMENT]: [ROLE.KHACH_THUE],
  [ROUTES.FINANCIAL_IMPORT]: [ROLE.TP_KDTC, ROLE.NV_KDTC],
  [ROUTES.FINANCIAL_REPORTS]: [ROLE.BQL, ROLE.TP_KDTC],
  [ROUTES.METER_READINGS]: [ROLE.TP_VHBT, ROLE.NV_VHBT],
  [ROUTES.INCIDENTS]: [ROLE.BQL, ROLE.TP_VHBT, ROLE.NV_VHBT, ROLE.KHACH_THUE],
  [ROUTES.MAINTENANCE_REPORTS]: [ROLE.BQL, ROLE.TP_VHBT],
  [ROUTES.NOTIFICATIONS]: [
    ROLE.BQL,
    ROLE.QTV,
    ROLE.TP_KDTC,
    ROLE.NV_KDTC,
    ROLE.TP_VHBT,
    ROLE.NV_VHBT,
    ROLE.KHACH_THUE,
  ],
};

const item = (key, label, icon, allowedRoles, badgeKey = null) => ({
  key,
  label,
  icon,
  allowedRoles,
  badgeKey,
});

export const menuItems = [
  item(ROUTES.DASHBOARD, "Bảng điều khiển", AppstoreOutlined, routePermissions[ROUTES.DASHBOARD]),
  item(ROUTES.ACCOUNTS, "Quản lý tài khoản", TeamOutlined, routePermissions[ROUTES.ACCOUNTS]),
  item(ROUTES.RBAC, "Vai trò & quyền", SafetyCertificateOutlined, routePermissions[ROUTES.RBAC]),
  item(ROUTES.AUDIT, "Nhật ký thao tác", AuditOutlined, routePermissions[ROUTES.AUDIT]),
  item(ROUTES.PREMISES, "Mặt bằng", ShopOutlined, routePermissions[ROUTES.PREMISES]),
  item(ROUTES.CONTRACTS, "Hợp đồng", FileProtectOutlined, routePermissions[ROUTES.CONTRACTS]),
  item(ROUTES.MY_CONTRACTS, "Hợp đồng của tôi", ProfileOutlined, routePermissions[ROUTES.MY_CONTRACTS]),
  item(ROUTES.RENT_REQUESTS, "Yêu cầu thuê thêm", HomeOutlined, routePermissions[ROUTES.RENT_REQUESTS], "rent_requests"),
  item(ROUTES.DEBTS, "Công nợ", CreditCardOutlined, routePermissions[ROUTES.DEBTS], "debts"),
  item(ROUTES.MY_DEBTS, "Công nợ & Thanh toán", CreditCardOutlined, routePermissions[ROUTES.MY_DEBTS], "my_debts"),
  item(ROUTES.FINANCIAL_IMPORT, "Import tài chính", FileExcelOutlined, routePermissions[ROUTES.FINANCIAL_IMPORT], "import_errors"),
  item(ROUTES.FINANCIAL_REPORTS, "Báo cáo tài chính", PieChartOutlined, routePermissions[ROUTES.FINANCIAL_REPORTS]),
  item(ROUTES.METER_READINGS, "Chỉ số điện nước", ThunderboltOutlined, routePermissions[ROUTES.METER_READINGS]),
  item(ROUTES.INCIDENTS, "Sự cố bảo trì", ToolOutlined, routePermissions[ROUTES.INCIDENTS], "incidents"),
  item(ROUTES.MAINTENANCE_REPORTS, "Báo cáo bảo trì", ContainerOutlined, routePermissions[ROUTES.MAINTENANCE_REPORTS]),
  item(ROUTES.NOTIFICATIONS, "Thông báo", NotificationOutlined, routePermissions[ROUTES.NOTIFICATIONS], "notifications"),
];
