import { CheckOutlined, PlusOutlined, ToolOutlined, UserAddOutlined } from "@ant-design/icons";
import { Button, Form, Input, InputNumber, Modal, Space, message } from "antd";
import { useCallback, useState } from "react";
import PageHeader from "../../components/common/PageHeader";
import ResponsiveTable from "../../components/common/ResponsiveTable";
import StatusTag from "../../components/common/StatusTag";
import { ROLE } from "../../constants/roles";
import { useAuth } from "../../hooks/useAuth";
import { useCrudList } from "../../hooks/useCrudList";
import { incidentService } from "../../services/maintenanceService";
import { showApiError } from "../../services/apiClient";
import { pick, pickId, formatDate } from "../../utils/data";
export default function IncidentListPage(){
 const {role}=useAuth(); const isTenant=role===ROLE.KHACH_THUE; const [open,setOpen]=useState(false); const [action,setAction]=useState(null); const [row,setRow]=useState(null); const [form]=Form.useForm(); const fetcher=useCallback((p)=>incidentService.list(p),[]); const {items,loading,reload}=useCrudList(fetcher,{page:1,page_size:20});
 const openAction=(type,r)=>{setAction(type); setRow(r); form.resetFields(); setOpen(true)};
 const submit=async()=>{const id=pickId(row,["ma_su_co","MASUCO"]); try{const v=form.getFieldsValue(true); if(action==="create") await incidentService.create(v); if(action==="review") await incidentService.review(id,{ket_qua:v.ket_qua||"DUYET",ly_do_tu_choi:v.ly_do_tu_choi}); if(action==="assign") await incidentService.assign(id,v); if(action==="result") await incidentService.updateResult(id,v); if(action==="cost") await incidentService.updateCost(id,v); message.success("Thao tác thành công"); setOpen(false); reload();}catch(e){showApiError(e)}};
 const columns=[{title:"Mã sự cố",render:(_,r)=>pick(r,["ma_su_co","MASUCO"])},{title:"Mặt bằng",render:(_,r)=>pick(r,["ma_mat_bang","MAMB"])},{title:"Khách thuê",render:(_,r)=>pick(r,["ma_khach_thue","MAKH"])},{title:"Mô tả",render:(_,r)=>pick(r,["mo_ta","MOTA"])},{title:"Ngày gửi",render:(_,r)=>formatDate(pick(r,["ngay_gui","NGAYGUI"]))},{title:"Trạng thái",render:(_,r)=><StatusTag value={pick(r,["trang_thai","TRANGTHAI"])}/>},{title:"Thao tác",align:"right",render:(_,r)=><Space wrap>{role===ROLE.BQL?<Button icon={<CheckOutlined/>} onClick={()=>openAction("review",r)}>Duyệt</Button>:null}{role===ROLE.TP_VHBT?<Button icon={<UserAddOutlined/>} onClick={()=>openAction("assign",r)}>Phân công</Button>:null}{[ROLE.TP_VHBT,ROLE.NV_VHBT].includes(role)?<><Button icon={<ToolOutlined/>} onClick={()=>openAction("result",r)}>Kết quả</Button><Button onClick={()=>openAction("cost",r)}>Chi phí</Button></>:null}</Space>}];
 const modalTitle={create:"Gửi sự cố bảo trì",review:"Duyệt sự cố",assign:"Phân công xử lý",result:"Cập nhật kết quả",cost:"Nhập chi phí"}[action];
 return <><PageHeader title={isTenant?"Yêu cầu sửa chữa":"Sự cố bảo trì"} breadcrumb={["Bảo trì","Sự cố"]} actionText={isTenant?"Gửi sự cố":null} actionIcon={<PlusOutlined/>} onAction={()=>{setAction("create");setRow({});form.resetFields();setOpen(true)}}/><ResponsiveTable rowKey={(r)=>pickId(r,["ma_su_co","MASUCO"])} columns={columns} dataSource={items} loading={loading}/><Modal title={modalTitle} open={open} onCancel={()=>setOpen(false)} onOk={submit}>{action==="create"&&<Form form={form} layout="vertical"><Form.Item name="ma_mat_bang" label="Mã mặt bằng" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="mo_ta" label="Mô tả" rules={[{required:true}]}><Input.TextArea rows={4}/></Form.Item></Form>}{action==="review"&&<Form form={form} layout="vertical"><Form.Item name="ket_qua" label="Kết quả" initialValue="DUYET"><Input/></Form.Item><Form.Item name="ly_do_tu_choi" label="Lý do từ chối nếu có"><Input.TextArea/></Form.Item></Form>}{action==="assign"&&<Form form={form} layout="vertical"><Form.Item name="ma_nhan_vien_xu_ly" label="Mã nhân viên xử lý" rules={[{required:true}]}><Input placeholder="NV_VHBT_001"/></Form.Item></Form>}{action==="result"&&<Form form={form} layout="vertical"><Form.Item name="ket_qua" label="Kết quả" rules={[{required:true}]}><Input.TextArea/></Form.Item><Form.Item name="ngay_hoan_thanh" label="Ngày hoàn thành"><Input type="datetime-local"/></Form.Item></Form>}{action==="cost"&&<Form form={form} layout="vertical"><Form.Item name="chi_phi" label="Chi phí" rules={[{required:true}]}><InputNumber style={{width:"100%"}} min={0}/></Form.Item></Form>}</Modal></>;
}
